# Generated by Django 4.2.25 on 2025-10-29 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NormalizedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("normalized", models.BooleanField(default=False)),
                ("received_at", models.DateField(default=django.utils.timezone.now)),
                ("dedupe_key", models.CharField(db_index=True, max_length=200)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.normalizedaddress",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dedupe_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("price", models.IntegerField()),
                ("beds", models.IntegerField()),
                ("baths", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("sources", models.JSONField(default=list)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.normalizedaddress",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["price", "beds"], name="partners_li_price_73ba20_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="partners_li_updated_5edcd0_idx"
                    ),
                ],
            },
        ),
    ]
